# Generated by Django 4.1 on 2024-07-09 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='score',
            table='score_user',
        ),
    ]
