# Generated by Django 4.1 on 2024-07-15 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_score_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
