# Generated by Django 4.1 on 2024-07-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20240715_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('afrique_best_score', models.IntegerField(default=0)),
                ('amerique_best_score', models.IntegerField(default=0)),
                ('asie_best_score', models.IntegerField(default=0)),
                ('europe_best_score', models.IntegerField(default=0)),
                ('moyen_orient_best_score', models.IntegerField(default=0)),
                ('oceanie_best_score', models.IntegerField(default=0)),
                ('flag_best_score', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'best_score_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CurrentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('afrique_current_score', models.IntegerField(default=0)),
                ('amerique_current_score', models.IntegerField(default=0)),
                ('asie_current_score', models.IntegerField(default=0)),
                ('europe_current_score', models.IntegerField(default=0)),
                ('moyen_orient_current_score', models.IntegerField(default=0)),
                ('oceanie_current_score', models.IntegerField(default=0)),
                ('flag_current_score', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'current_score_user',
                'managed': False,
            },
        ),
    ]
