# Generated by Django 4.1 on 2024-07-15 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_bestscore_currentscore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bestscore',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='currentscore',
            options={'managed': True},
        ),
    ]
